#!/usr/bin/env python3

"""Stage Servomotor Arduino library sources + main firmware file into this repo.

This script is used by [`build_and_upload.py`](build_and_upload.py:1).

It performs two tasks:

1) Copy the required files from ../../Servomotor/Arduino_library into lib/Servomotor/
2) Copy a single servomotor*.firmware file from the project root into a given
   fwfs staging directory, renaming it to comply with SPIFFS name limits:
   - leading "servomotor" -> "SM"
   - strip trailing ".firmware"
   - require <= 31 chars
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path


def _die(msg: str, exit_code: int = 2) -> "NoReturn":
    sys.stderr.write(f"ERROR: {msg}\n")
    raise SystemExit(exit_code)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _servomotor_arduino_lib_dir(repo_root: Path) -> Path:
    # This repo lives under: .../AI_testing/ESP32_STM32_programmer
    # Servomotor lives at:   .../Servomotor
    return (repo_root / "../../Servomotor/Arduino_library").resolve()


def _normalize_basename(
    *,
    incoming_filename: str,
    required_prefix: str,
    replacement_prefix: str,
    strip_suffix: str | None,
    strip_suffix_case_insensitive: bool,
    max_len: int = 31,
) -> str:
    # Mirrors [`cpp.filename_normalizer::normalize_basename()`](src/filename_normalizer.cpp:1)
    # but implemented in Python for host-side staging.
    base = incoming_filename.replace("\\", "/").split("/")[-1]
    if not base.startswith(required_prefix):
        _die(f"filename must start with {required_prefix!r}")
    base = replacement_prefix + base[len(required_prefix) :]
    if strip_suffix:
        if strip_suffix_case_insensitive:
            if base.lower().endswith(strip_suffix.lower()):
                base = base[: -len(strip_suffix)]
        else:
            if base.endswith(strip_suffix):
                base = base[: -len(strip_suffix)]
    if len(base) == 0:
        _die("normalized filename is empty")
    if len(base) > max_len:
        _die(f"normalized filename too long: {len(base)} chars (>{max_len}): {base!r}")
    if "/" in base or "\\" in base:
        _die("normalized filename contains a path separator")
    if not base.startswith(replacement_prefix):
        _die(f"normalized filename must start with {replacement_prefix!r}: {base!r}")
    return base


def _find_unique_host_servomotor_firmware(project_root: Path) -> Path:
    matches = sorted(p for p in project_root.glob("servomotor*.firmware") if p.is_file())
    if not matches:
        _die(
            "No servomotor firmware file found. Expected exactly one file matching 'servomotor*.firmware' in the project root."
        )
    if len(matches) > 1:
        listed = "\n".join(f"  - {p.name}" for p in matches)
        _die(
            "Multiple servomotor firmware files found in the project root matching 'servomotor*.firmware'.\n"
            "Remove/rename extras so exactly one remains, then retry.\n\n"
            f"Matches:\n{listed}"
        )
    return matches[0]


def _copy_required_arduino_library_files(src_dir: Path, dst_dir: Path) -> None:
    required = [
        "Servomotor.cpp",
        "Servomotor.h",
        "Communication.cpp",
        "Communication.h",
        "Commands.h",
        "DataTypes.cpp",
        "DataTypes.h",
        "Utils.h",
        "AutoGeneratedUnitConversions.cpp",
        "AutoGeneratedUnitConversions.h",
        "library.properties",
        "keywords.txt",
        "LICENSE",
        "README.md",
    ]

    dst_dir.mkdir(parents=True, exist_ok=True)

    for rel in required:
        sp = src_dir / rel
        if not sp.exists():
            _die(f"Servomotor Arduino library missing required file: {sp}")
        dp = dst_dir / rel
        shutil.copy2(sp, dp)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Stage Servomotor Arduino library + main firmware file for fwfs image")
    ap.add_argument(
        "--fwfs-data-dir",
        required=True,
        help="Directory to receive the renamed servomotor firmware file (input directory for buildfwfs)",
    )
    ap.add_argument(
        "--skip-library-copy",
        action="store_true",
        help="Skip copying Arduino library sources into lib/Servomotor (useful for debugging)",
    )
    args = ap.parse_args(argv)

    repo_root = _repo_root()
    project_root = repo_root
    fwfs_data_dir = Path(args.fwfs_data_dir).resolve()
    if not fwfs_data_dir.exists() or not fwfs_data_dir.is_dir():
        _die(f"--fwfs-data-dir is not a directory: {fwfs_data_dir}")

    # 1) Copy Arduino library sources.
    if not args.skip_library_copy:
        src = _servomotor_arduino_lib_dir(repo_root)
        if not src.exists():
            _die(f"Servomotor Arduino library not found at: {src}")
        dst = repo_root / "lib/Servomotor"
        _copy_required_arduino_library_files(src, dst)
        sys.stdout.write(f"[info] Copied Servomotor Arduino library into: {dst}\n")

    # 2) Stage the firmware file into fwfs staging dir.
    fw = _find_unique_host_servomotor_firmware(project_root)
    renamed = _normalize_basename(
        incoming_filename=fw.name,
        required_prefix="servomotor",
        replacement_prefix="SM",
        strip_suffix=".firmware",
        strip_suffix_case_insensitive=False,
    )
    out = fwfs_data_dir / renamed
    shutil.copy2(fw, out)
    sys.stdout.write(f"[info] Staged servomotor firmware: {fw.name} -> {out}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
